import React from 'react';
import SeoLandingTemplate from '../landing-os/SeoLandingTemplate';

import instagram from './content/instagram-marketing-ai.json';
import facebook  from './content/facebook-marketing-ai.json';
import linkedin  from './content/linkedin-marketing-ai.json';
import reddit    from './content/reddit-marketing-ai.json';
import youtube   from './content/youtube-marketing-ai.json';
import tiktok    from './content/tiktok-marketing-ai.json';

/*
  Phase 4 — Per-platform AI marketing landing pages. All 6 reuse the
  Round 2 SeoLandingTemplate. Content is generated by
  /app/backend/scripts/generate_platform_pages.py.
*/

export const InstagramMarketingAI = () => <SeoLandingTemplate content={instagram} />;
export const FacebookMarketingAI  = () => <SeoLandingTemplate content={facebook} />;
export const LinkedInMarketingAI  = () => <SeoLandingTemplate content={linkedin} />;
export const RedditMarketingAI    = () => <SeoLandingTemplate content={reddit} />;
export const YouTubeMarketingAI   = () => <SeoLandingTemplate content={youtube} />;
export const TikTokMarketingAI    = () => <SeoLandingTemplate content={tiktok} />;
