import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, Check, X, Sparkles, Compass } from 'lucide-react';
import CVNavbar from '../../components/cv/CVNavbar';
import CVBackdrop from '../../components/cv/CVBackdrop';
import CVFooter from '../../components/cv/CVFooter';
import CVFaq from '../../components/cv/CVFaq';
import CVSeo, {
  ORG_SCHEMA, SOFTWARE_SCHEMA, buildFaqSchema, buildBreadcrumbSchema,
} from '../../components/cv/CVSeo';
import CVBreadcrumbs from '../../components/cv/CVBreadcrumbs';
import { SelectAgentModal, AgentChatModal } from '../../components/Modals';

/**
 * Per-platform visual signature (Phase 6 polish). Each platform page
 * carries a unique accent palette echoing its channel brand identity
 * — Instagram coral→fuchsia, TikTok magenta→cyan, LinkedIn electric
 * blue, etc. The base SaaS landing pages (marketing-os,
 * seller-acquisition, ai-campaign-generator, competitor-analysis,
 * asset-analysis) keep the default violet/cyan brand combo.
 *
 * `accent.primary` / `accent.secondary` are used as CSS variables on
 * the page root so any nested element can opt-in via inline style.
 */
const PLATFORM_ACCENTS = {
  'instagram-marketing-ai': {
    primary:    '#FF3CAC',    // hot pink
    secondary:  '#FFB347',    // amber-coral
    pulse:      '#FF3CAC',
    rgb:        '255, 60, 172',
  },
  'tiktok-marketing-ai': {
    primary:    '#FE2C55',    // TikTok red
    secondary:  '#25F4EE',    // TikTok cyan
    pulse:      '#25F4EE',
    rgb:        '254, 44, 85',
  },
  'linkedin-marketing-ai': {
    primary:    '#0A66C2',    // LinkedIn blue
    secondary:  '#38BDF8',    // sky
    pulse:      '#38BDF8',
    rgb:        '10, 102, 194',
  },
  'youtube-marketing-ai': {
    primary:    '#FF0033',    // YouTube red
    secondary:  '#FF6B6B',    // soft coral
    pulse:      '#FF6B6B',
    rgb:        '255, 0, 51',
  },
  'facebook-marketing-ai': {
    primary:    '#1877F2',    // Facebook blue
    secondary:  '#42A5F5',    // light blue
    pulse:      '#42A5F5',
    rgb:        '24, 119, 242',
  },
  'reddit-marketing-ai': {
    primary:    '#FF4500',    // Reddit orange
    secondary:  '#FFD635',    // award gold
    pulse:      '#FF4500',
    rgb:        '255, 69, 0',
  },
};

const DEFAULT_ACCENT = {
  primary:    '#A78BFA',      // violet-400
  secondary:  '#67E8F9',      // cyan-300
  pulse:      '#22D3EE',
  rgb:        '167, 139, 250',
};

/**
 * Reusable visual shell for /marketing-os, /seller-acquisition,
 * /ai-campaign-generator, /competitor-analysis, /asset-analysis.
 *
 * Driven 100% from the `content` JSON object generated by
 * `/app/backend/scripts/generate_seo_landings.py` so the page bodies
 * stay swappable without touching React.
 */
const SeoLandingTemplate = ({ content }) => {
  const navigate = useNavigate();
  const meta = content.__meta__ || {};
  const [selectOpen, setSelectOpen] = useState(false);
  const [chatOpen, setChatOpen] = useState(false);
  const [activeAgent, setActiveAgent] = useState(null);

  const accent = PLATFORM_ACCENTS[meta.slug] || DEFAULT_ACCENT;
  // CSS custom properties — nested elements opt-in via style attribute.
  const accentStyle = {
    '--accent-primary':   accent.primary,
    '--accent-secondary': accent.secondary,
    '--accent-pulse':     accent.pulse,
    '--accent-rgb':       accent.rgb,
  };

  const breadcrumbs = [
    { label: 'Home', path: '/' },
    { label: meta.kicker || 'Solution', path: `/${meta.slug}` },
  ];

  return (
    <div
      className="min-h-screen cv-dark antialiased"
      data-testid={`seo-landing-${meta.slug}`}
      data-accent={meta.slug in PLATFORM_ACCENTS ? meta.slug : 'default'}
      style={accentStyle}
    >
      <CVSeo
        title={meta.title}
        description={meta.meta}
        path={`/${meta.slug}`}
        schema={[
          ORG_SCHEMA,
          SOFTWARE_SCHEMA,
          buildBreadcrumbSchema(breadcrumbs),
          buildFaqSchema((content.faq || []).map((f) => ({
            question: f.q, answer: f.a,
          }))),
        ]}
      />
      <CVNavbar onGetStarted={() => setSelectOpen(true)} />

      {/* HERO */}
      <section className="relative pt-32 pb-16 overflow-hidden">
        <CVBackdrop variant="hero" />
        <div className="relative max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <CVBreadcrumbs items={[{ label: meta.kicker || 'Solution' }]} className="mb-5" />
          <div
            className="inline-flex items-center gap-2 px-3 h-7 rounded-full cv-glass text-[11px] font-semibold uppercase tracking-[0.16em] text-zinc-300 mb-6"
            style={{ borderColor: 'rgba(var(--accent-rgb), 0.25)' }}
          >
            <span
              className="w-1.5 h-1.5 rounded-full cv-pulse"
              style={{ backgroundColor: 'var(--accent-pulse)' }}
            />
            {meta.kicker}
          </div>
          <motion.h1
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
            className="cv-display text-5xl sm:text-6xl lg:text-7xl font-semibold text-white leading-[0.95]"
            data-testid="seo-landing-h1"
          >
            {meta.h1_lead}{' '}
            <span
              className="cv-gradient-text"
              style={{
                backgroundImage:
                  'linear-gradient(120deg, var(--accent-primary), var(--accent-secondary))',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
              }}
            >{meta.h1_accent}</span>
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.1 }}
            className="mt-6 max-w-2xl text-[17px] leading-relaxed text-zinc-400"
          >
            {content.hero_subhead}
          </motion.p>

          {/* Hero bullets */}
          {Array.isArray(content.hero_bullets) && (
            <div className="mt-7 grid sm:grid-cols-2 gap-2.5 max-w-2xl">
              {content.hero_bullets.map((b) => (
                <div key={b} className="flex items-start gap-2.5 text-[14px] text-zinc-300">
                  <Check
                    size={15}
                    className="mt-0.5 shrink-0"
                    style={{ color: 'var(--accent-secondary)' }}
                  />
                  <span>{b}</span>
                </div>
              ))}
            </div>
          )}

          <div className="mt-9 flex flex-wrap items-center gap-3">
            <button
              onClick={() => navigate('/dashboard')}
              className="cv-btn-primary inline-flex items-center gap-2 text-[14px] font-semibold px-6 h-12 rounded-full"
              data-testid="seo-landing-cta-primary"
            >
              Start Your First Mission <ArrowRight size={15} />
            </button>
            <button
              onClick={() => document.getElementById('seo-faq')?.scrollIntoView({ behavior: 'smooth' })}
              className="cv-btn-secondary inline-flex items-center gap-2 text-[14px] font-semibold px-5 h-12 rounded-full"
              data-testid="seo-landing-cta-secondary"
            >
              Read the FAQ
            </button>
          </div>
        </div>
      </section>

      {/* BODY SECTIONS */}
      <section className="relative cv-dark pb-8" data-testid="seo-landing-sections">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-16">
          {(content.sections || []).map((s, idx) => (
            <motion.article
              key={`sec-${idx}`}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-80px' }}
              transition={{ duration: 0.5 }}
              className="cv-glass-strong rounded-3xl p-8 sm:p-10"
              data-testid={`seo-landing-section-${idx}`}
            >
              {s.kicker && (
                <span
                  className="text-[11px] uppercase tracking-[0.22em] font-semibold"
                  style={{ color: 'var(--accent-primary)' }}
                >
                  {s.kicker}
                </span>
              )}
              <h2 className="cv-display text-2xl sm:text-3xl font-semibold text-white mt-2 leading-tight">
                {s.heading}
              </h2>
              <p className="mt-4 text-[15px] leading-relaxed text-zinc-300 whitespace-pre-line">
                {s.body}
              </p>
              {Array.isArray(s.bullets) && s.bullets.length > 0 && (
                <ul className="mt-5 space-y-2.5">
                  {s.bullets.map((b, bi) => (
                    <li key={bi} className="flex items-start gap-2.5 text-[14px] text-zinc-300">
                      <Sparkles size={13} className="text-cyan-300 mt-1 shrink-0" />
                      <span>{b}</span>
                    </li>
                  ))}
                </ul>
              )}
            </motion.article>
          ))}
        </div>
      </section>

      {/* COMPARISON TABLE — "Old way vs CortexViral way" */}
      {content.comparison && (
        <section className="relative cv-dark py-16" data-testid="seo-landing-comparison">
          <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
            <h2 className="cv-display text-3xl sm:text-4xl font-semibold text-white text-center leading-tight">
              {content.comparison.title}
            </h2>
            <div className="mt-10 grid md:grid-cols-2 gap-4">
              <div className="cv-glass rounded-3xl p-7 border border-rose-500/20">
                <div className="text-[11px] uppercase tracking-[0.22em] text-rose-300 font-semibold mb-3">
                  {content.comparison.left?.label || 'Without CortexViral'}
                </div>
                <ul className="space-y-3">
                  {(content.comparison.left?.items || []).map((it, i) => (
                    <li key={i} className="flex items-start gap-2.5 text-[14px] text-zinc-400">
                      <X size={14} className="text-rose-400/70 mt-1 shrink-0" />
                      <span>{it}</span>
                    </li>
                  ))}
                </ul>
              </div>
              <div
                className="cv-glass-strong rounded-3xl p-7 cv-glow-violet"
                style={{
                  borderColor: 'rgba(var(--accent-rgb), 0.4)',
                  boxShadow: '0 0 60px -20px rgba(var(--accent-rgb), 0.45)',
                }}
              >
                <div
                  className="text-[11px] uppercase tracking-[0.22em] font-semibold mb-3"
                  style={{ color: 'var(--accent-secondary)' }}
                >
                  {content.comparison.right?.label || 'With CortexViral'}
                </div>
                <ul className="space-y-3">
                  {(content.comparison.right?.items || []).map((it, i) => (
                    <li key={i} className="flex items-start gap-2.5 text-[14px] text-zinc-100">
                      <Check
                        size={14}
                        className="mt-1 shrink-0"
                        style={{ color: 'var(--accent-secondary)' }}
                      />
                      <span>{it}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>
      )}

      {/* INTERNAL LINKS — Phase 6: every landing page links to ≥3 siblings */}
      {Array.isArray(content.internal_links) && content.internal_links.length > 0 && (
        <section className="relative cv-dark py-16" data-testid="seo-landing-internal-links">
          <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-10">
              <span className="text-[11px] uppercase tracking-[0.22em] text-violet-400 font-semibold">Explore the platform</span>
              <h2 className="cv-display text-3xl sm:text-4xl font-semibold text-white mt-2">
                More from the <span className="cv-gradient-text">CortexViral</span> OS
              </h2>
            </div>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {content.internal_links.map((lnk) => (
                <Link
                  key={lnk.slug}
                  to={`/${lnk.slug}`}
                  className="group cv-glass rounded-2xl p-5 hover:border-violet-400/40 transition-colors"
                  data-testid={`internal-link-${lnk.slug}`}
                >
                  <div className="flex items-center gap-2 mb-2">
                    <Compass size={14} className="text-cyan-300" />
                    <span className="text-[11px] uppercase tracking-wider text-zinc-500 font-semibold">
                      Related
                    </span>
                  </div>
                  <div className="text-[15px] font-semibold text-white group-hover:text-cyan-300 transition-colors">
                    {lnk.title}
                  </div>
                  <div className="text-[12.5px] text-zinc-400 mt-2 leading-relaxed">
                    {lnk.blurb}
                  </div>
                  <div className="mt-3 inline-flex items-center gap-1 text-[12px] font-semibold text-violet-300 group-hover:gap-2 transition-all">
                    Read more <ArrowRight size={12} />
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* FAQ */}
      <div id="seo-faq" data-testid="seo-landing-faq">
        <CVFaq
          faqs={content.faq || []}
          title={<>Answers about <span className="cv-gradient-text">{meta.kicker?.toLowerCase()}</span></>}
        />
      </div>

      {/* FINAL CTA */}
      <section className="relative cv-dark py-20" data-testid="seo-landing-final-cta">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="cv-display text-4xl sm:text-5xl font-semibold text-white leading-[0.98]">
            {content.final_cta_heading}
          </h2>
          <p className="mt-5 text-zinc-400 text-[15px] max-w-xl mx-auto leading-relaxed">
            {content.final_cta_body}
          </p>
          <div className="mt-8 flex items-center justify-center gap-3 flex-wrap">
            <button
              onClick={() => navigate('/dashboard')}
              className="cv-btn-primary inline-flex items-center gap-1.5 px-6 h-12 rounded-full text-[14px] font-semibold"
              data-testid="seo-landing-final-cta-primary"
            >
              Start Your First Mission <ArrowRight size={15} />
            </button>
            <button
              onClick={() => navigate('/pricing')}
              className="cv-btn-secondary inline-flex items-center gap-1.5 px-6 h-12 rounded-full text-[14px] font-semibold"
            >
              See pricing
            </button>
          </div>
        </div>
      </section>

      <CVFooter />

      <SelectAgentModal
        open={selectOpen}
        onClose={() => setSelectOpen(false)}
        onSelect={(a) => {
          setActiveAgent(a);
          setSelectOpen(false);
          setTimeout(() => setChatOpen(true), 120);
        }}
      />
      <AgentChatModal
        open={chatOpen}
        onClose={() => setChatOpen(false)}
        agent={activeAgent}
        onBack={() => { setChatOpen(false); setSelectOpen(true); }}
      />
    </div>
  );
};

export default SeoLandingTemplate;
